# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-29 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.IntegerField(),
        ),
    ]
