# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-29 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20170829_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='addr',
            field=models.CharField(default=b'', max_length=200),
        ),
        migrations.AddField(
            model_name='account',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.CharField(default=b'', max_length=200),
        ),
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(default=b'', max_length=200),
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(default=b'', max_length=200),
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(default=b'', max_length=200),
        ),
    ]
